import Head from 'next/head'
import Image from 'next/image'
import Intro from '../components/sections/Intro'
import Tech from '../components/sections/Tech'
import g from '../styles/global.module.css'

export default function Home() {
  return (
    <div className={g.Cont}>
      <Head>
        <title>Hari Raghav Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro></Intro>
     
      <div id="tech" style={{height:"30px",margin:"5rem 0",border:"0px solid red",}}></div>
      <Tech></Tech>
      
    </div>
  )
}
